#!/usr/bin/env python3
"""Regenerate docs/EFFECTS.md from the effect registry.

Run this after adding or changing an effect so the catalogue never drifts:

    python3 scripts/gen_effects_doc.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from mvfx.effects import EFFECTS, PRESET_HELP, PRESETS, STAGE_NAMES, list_effects  # noqa: E402

TARGET = Path(__file__).resolve().parent.parent / "docs" / "EFFECTS.md"


def main() -> int:
    out = ["# Effect catalogue", "", "Generated by `scripts/gen_effects_doc.py` — edit the "
           "effects, re-run the script.", ""]

    out += ["## Looks (presets)", "", "A look is a named bundle of effects. Use as "
            "`--preset NAME` (or `-e 'preset:NAME'`).", ""]
    out.append("| look | contains | what it's for |")
    out.append("| --- | --- | --- |")
    for name in sorted(PRESETS):
        chain = ", ".join(a.name for a in PRESETS[name]) or "—"
        out.append(f"| `{name}` | {chain} | {PRESET_HELP.get(name, '')} |")
    out.append("")

    out += ["## Effects", ""]
    current = None
    for eff in list_effects():
        stage = STAGE_NAMES.get(eff.stage, eff.stage)
        if stage != current:
            current = stage
            out += [f"### {stage}", ""]
        params = ""
        if eff.params:
            params = "(" + ":".join(f"{k}={v}" for k, v in eff.params.items()) + ")"
        out.append(f"#### `{eff.name}{params}`")
        out.append("")
        out.append(eff.help)
        out.append("")
        if eff.params:
            out.append("| parameter | default |")
            out.append("| --- | --- |")
            for key, value in eff.params.items():
                out.append(f"| `{key}` | `{value}` |")
            out.append("")
        if eff.aliases:
            out.append(f"aliases: {', '.join(f'`{a}`' for a in eff.aliases)}")
            out.append("")

    out += [
        "## Spec syntax",
        "",
        "```",
        "bloom                        # effect with default parameters",
        "bloom(sigma=22:opacity=0.6)  # with parameters (colon separated)",
        "teal_orange+grain(level=10)  # several effects, combined with +",
        "preset:cinematic             # a look",
        "```",
        "",
        "Effects are always applied in stage order (geometry -> grade -> blend ->",
        "artifact -> light -> frame -> text), regardless of the order you write them.",
        "",
    ]
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(out) + "\n")
    print(f"wrote {TARGET} ({len(list_effects())} effects, {len(PRESETS)} looks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
